### ISSUE TITLE
Problem While accessing Volunteer/Reports Link

### ISSUE THREAD

**Issue by tudorian** [nursix/eden#41]
Url: http://localhost:8000/eden/vol/volunteer/report 

Traceback:

Traceback (most recent call last):
  File "/home/dev/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/dev/web2py/applications/eden/controllers/vol.py", line 514, in <module>
  File "/home/dev/web2py/gluon/globals.py", line 393, in <lambda>
    self._caller = lambda f: f()
  File "/home/dev/web2py/applications/eden/controllers/vol.py", line 53, in volunteer
    return s3db.vol_volunteer_controller()
  File "applications/eden/modules/s3db/vol.py", line 906, in vol_volunteer_controller
    return current.rest_controller("hrm", "human_resource")
  File "/home/dev/web2py/applications/eden/models/00_utils.py", line 198, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 616, in __call__
    output = handler(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1680, in __call__
    output = self.apply_method(r, **attr)
  File "applications/eden/modules/s3/s3report.py", line 85, in apply_method
    output = self.report(r, **attr)
  File "applications/eden/modules/s3/s3report.py", line 161, in report
    pivotdata = pivottable.json(maxrows=maxrows, maxcols=maxcols)
  File "applications/eden/modules/s3/s3report.py", line 1915, in json
    for fact in facts:
UnboundLocalError: local variable 'facts' referenced before assignment

**Comment by nursix** [comment]
Which revision of the code? The current revision does not seem to have this problem.

Why are you reporting issues to my repository, anyway?

**Comment by tudorian** [comment]
Sorry my mistake.
